mergeservice/urls.py
from django.urls import path
from . import views

app_name = "mergeservice"
urlpatterns = [
    path("authorisation/<str:pk>/", views.Authorasation.as_view(), name="Authorasation"),
    path("", views.Main_page.as_view(), name="Main_page"),
    path("about_us/", views.About_us_view.as_view(), name="About_us_view"),
    path("company_creating/", views.Company_creating.as_view(), name="Company_creating"),
    path("company_cabinet/<str:pk>/", views.Company_cabinet.as_view(), name='Company_cabinet'),
    path("join/<str:pk>/", views.Join_company.as_view(), name='Join_company')
]

socialmerge/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mergeservice.urls'))
]

mergeservice/forms.py
from cProfile import label

from django import forms
from django.forms.models import model_to_dict
from phonenumber_field.modelfields import PhoneNumberField
from . import models
from django.core.validators import MinValueValidator, MaxValueValidator
import datetime

from . import views


class Sign_up_form(forms.Form):
    First_name = forms.CharField(max_length=50, required=True, label='First name')
    Last_name = forms.CharField(max_length=60, required=True, label='Last name')
    login = forms.CharField(max_length=60, required=True, label='Login')
    password = forms.CharField(max_length=60, required=True, label='Password', widget=forms.PasswordInput)
    address = forms.CharField(max_length=90, label='Address')
    city = forms.CharField(max_length=7, label="City", required=True)
    postal_code = forms.CharField(max_length=10, label="Postal code")
    administrative_unit = forms.CharField(max_length=30, label='Administrative unit')
    build_number = forms.CharField(max_length=10, required=10, label='Build number')
    flat_number = forms.IntegerField(validators=[
        MinValueValidator(0),
        MaxValueValidator(2000)
    ])
    birth_date = forms.DateField(help_text='Your birthday(dd/mm/yyyy)', validators=[
            MinValueValidator(datetime.date(day=1, month=1, year=1700)),  # Minimum date: Jan 1, 2023
            MaxValueValidator(datetime.date.today()),  # Maximum date: Dec 31, 2023
        ], widget=forms.TextInput(attrs={'type': 'date'}), label="Birth date")

class Authorisation_form(forms.Form):
    First_name = forms.CharField(max_length=50, required=True, label='First name')
    Last_name = forms.CharField(max_length=60, required=True, label='Last name')
    login = forms.CharField(max_length=60, required=True, label='Login')
    password = forms.CharField(max_length=60, required=True, label='Password', widget=forms.PasswordInput)


class organisation_create(forms.Form):
# class organisation_create(forms.ModelForm):
    name = forms.CharField(max_length=75, required=True, label="Org. Name")
    address = forms.CharField(max_length=90, label='Main office address(or )')
    city = forms.CharField(max_length=25)
    postal_code = forms.CharField(max_length=10)
    administrative_unit = forms.CharField(max_length=50, required=True)
    mail = forms.EmailField(required=True, max_length=100, label='Email')
    flat_number = forms.IntegerField(validators=[
        MinValueValidator(0),
        MaxValueValidator(2000)
    ])
    nip = forms.IntegerField(required=True)
    krs = forms.IntegerField(required=True)
    description = forms.CharField(max_length=1000, widget=forms.Textarea, required=True)
    # class Meta:
    #     model = models.organisations
    #     fields = ["name", "address", "city", "postal_code", "administrative_unit", "mail", "flat_number", "nip", "krs", "description", "owner"]

class org_join(forms.ModelForm):
    # first_name = forms.CharField(max_length=50, required=True, label="First name")
    # surname = forms.CharField(max_length=60, required=True, label="Surname")



    # description = forms.CharField(max_length=1000, widget=forms.Textarea, required=True)
    # phone_number = PhoneNumberField()
    # class Meta:
    #     model = models.join_requests
    #     fields= ["user", "organisation", "description", "phone_number"]
    email = forms.EmailField(max_length=150, required=True, label="email")
    description = forms.CharField(max_length=1000, widget=forms.Textarea, required=True)
    phone_number = PhoneNumberField()
    class Meta:
        model = models.join_requests
        fields= ["email", "description", "phone_number"]



    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     # Customize author field if needed
    #     self.fields['owner'].queryset = models.users.objects.values('name')
    #     views.logger.info(model_to_dict(models.users.objects.values('name')))

    # def get_current_form_object(self, form_name):
    #     if form_name == "sign_up":
    #         form = Sign_up_form
    #         with open("you.txt", "w+") as gfg_file:
    #             gfg_file.write(form)
    #     elif form_name == "log_in":
    #         form = Authorisation_form
    #         with open("you.txt", "w+") as gfg_file:
    #             gfg_file.write(form)
    #     return form

# def get_current_form_object(form_name, *form_object):
#     if form_name == "sign_up":
#         form = Sign_up_form
#         with open("you.txt", "w+") as gfg_file:
#             gfg_file.write(form)
#         form_object = form
#     elif form_name == "log_in":
#         form = Authorisation_form
#         form_object = form
#         with open("you.txt", "w+") as gfg_file:
#             gfg_file.write(form)
#     return form_object

mergeservice/views.py
from lib2to3.fixes.fix_input import context
from os.path import exists

from aiohttp.web_response import Response
from django.contrib.auth import login
from django.db.models import QuerySet
from django.shortcuts import render, HttpResponseRedirect, reverse, redirect, HttpResponse
# from pyasn1_modules.rfc3279 import gnBasis
# from pyasn1_modules.rfc5280 import postal_code
from django.forms.models import model_to_dict


from . import forms
from .models import users, user_info, grants, organisations, organisation_needs, join_requests
from django.views import generic
from django.contrib import messages
import datetime
import logging
import ast

logger = logging.getLogger(__name__)
logging.basicConfig(filename='example.log', encoding='utf-8', level=logging.DEBUG)

def sort_cookies(request, info, response):
    try:
        accounts = ast.literal_eval(request.COOKIES.get('account_cookie'))
        # logger.info(accounts)
        for key in accounts.keys():
            accounts[key] = False
        user = info.get("login")
        if user in accounts.keys():
            accounts[user] = True
        else:
            accounts.update({user: True})
        response.set_cookie('account_cookie', accounts)
        return response
    except:
        response.set_cookie('account_cookie', {info.get("login"): True})
        return response

class Authorasation(generic.FormView):
    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    def get_queryset(self, request):
        ip_address = request.META.get('REMOTE_ADDR')
        if users.objects.filter(first_login_ip=ip_address, last_login_ip=ip_address) or users.objects.filter(login=request.COOKIES.get("account_cookie")):
            return HttpResponseRedirect('/')

    def get_pk_name(self, context):
        if self.kwargs.get('pk') == 'sign_up':
            context['link_name'] = 'log_in'
        else:
            context['link_name'] = 'sign_up'
        return context

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        return self.get_pk_name(context)

    def get_form_class(self):
        pk = self.kwargs.get('pk')
        if pk == 'sign_up':
            form_one = forms.Sign_up_form
            return form_one
        elif pk == 'log_in':
            form_two = forms.Authorisation_form
            return form_two



    template_name = "mergeservice/Authorisation.html"
    #success_url = '/'

    def post(self, request, *args, **kwargs):
        """


        Change cookies to
        dict {"name": False/True - activated}
        Read more about signed cookies next time!

        """
        response = HttpResponseRedirect('/')
        form = self.get_form()
        #logger.warning(form)
        #templ_name = reverse('mergeservice:Authorasation')
        if self.kwargs.get('pk') == 'log_in':
            if form.is_valid():
                ip_address = request.META.get('REMOTE_ADDR')
                info = form.cleaned_data
                #form.clean()
                # if users.objects.filter(first_login_ip=ip_address, last_login_ip=ip_address) or users.objects.filter(login=request.COOKIES.get("account_cookie")):
                if users.objects.filter(name=info.get('First_name'), last_name=info.get('Last_name'), login=info.get('login'), password=info.get('password')):
                    #form.save()
                    """
                    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                    """
                    users.objects.filter(login=info.get('login')).update(last_login_ip=ip_address)
                    return sort_cookies(request, info, response)
                else:
                    messages.error(request, "There was an error with your form.")
                    return render(request, 'mergeservice/Authorisation.html', {'link_name':"sign_up", 'form':form})
                    #return Response({'link_name':"log_in", 'form':form})
        elif self.kwargs.get('pk') == 'sign_up':
            if form.is_valid():
                ip_address = request.META.get('REMOTE_ADDR')
                #     if not (users.objects.filter(first_login_ip=ip_address, last_login_ip=ip_address) or users.objects.filter(login=request.COOKIES.get("account_cookie"))):
                info = form.cleaned_data
                form.clean()
                #name=info.get('First_name'), last_name=info.get('Last_name'), password=info.get('password') - DELETED
                if not users.objects.filter(login=info.get('login')):
                    users.objects.create(name=info.get('First_name'), last_name=info.get('Last_name'), login=info.get('login'), password=info.get('password'), first_login_ip=ip_address, last_login_ip=ip_address, created_at=datetime.datetime.today().strftime('%d-%m-%Y'))
                    main_user = users.objects.get(login=info.get('login'))
                    user_info.objects.create(address=info.get('address'), city=info.get('city'), postal_code=info.get('postal_code'), administrative_unit=info.get('administrative_unit'), build_number=info.get('build_number'), flat_number=info.get('flat_number'), birth_date=info.get('birth_date'), users_id=main_user)
                    return sort_cookies(request, info, response)
                else:
                    messages.error(request, "That user exists, try to log in!")
                    return render(request, 'mergeservice/Authorisation.html', {'link_name': "log_in", 'form': form})
            else:
                messages.error(request, "Oh, fuck!")
                return render(request, 'mergeservice/Authorisation.html', {'link_name': "log_in", 'form': form})

            #Add invalid form

            #     else:
            #         messages.error(request, "There was an error with your form.")
            # # else:
            #     self.send_problem_mess()
        # return render(request, templ_name, {'form': form})
        #return redirect(f"/authorisation/{self.kwargs.get('pk')}/"))

        #return render(request, 'mergeservice/authorisation.html', {"form": form, 'link_name': ['log_in' if self.kwargs.get('pk') == 'sign_up' else 'sign_up'][0]})
                # context = super().get_context_data()
                # context['problem_message'] = 'Hallo! Deutsch?'
                # return context


class Main_page(generic.ListView):
    template_name = "mergeservice/main_page.html"
    context_object_name = 'grants'

    def seperate_prof_companies(self):
        dict_1 = {}
        for i in list(organisations.objects.filter(org_status=1, rendered=1).values()):
            dict_1.update({i.get('name'): [i.get("description"), i.get("address"), i.get("city")]})
        #logger.info(dict_1)
        return dict_1

    def seperate_non_prof_companies(self):
        dict_1 = {}
        for i in list(organisations.objects.filter(org_status=2, rendered=1).values()):
            dict_1.update({i.get('name'): [i.get("description"), i.get("address"), i.get("city")]})
        #logger.info(dict_1)
        return dict_1


    def get(self, request):
        db_execution = {}
        ip_address = request.META.get('REMOTE_ADDR')
        response = HttpResponseRedirect('/')
        def exctract_cookies(name: str):
            try:
                returned_data = ast.literal_eval(request.COOKIES.get(name))
                return returned_data
            except:
                return None
        accounts = exctract_cookies('account_cookie')
        key_value = ''
        if accounts:
            for key, value in accounts.items():
                if value == True:
                    try:
                        db_execution = users.objects.get(login=key)
                        key_value = key
                        break
                    except:
                        continue
            if db_execution:
                model_dict = model_to_dict(db_execution)
                if model_dict.get('first_login_ip') == ip_address or model_dict.get('last_login_ip') == ip_address:
                    logging.error(list(organisations.objects.values()))

                    return render(request, 'mergeservice/main_page.html', {'grants': grants.objects.values(), 'orgs_prof': self.seperate_prof_companies(), 'orgs_non_prof': self.seperate_non_prof_companies()})
                else:
                    # sort_cookies(request=request, info={'login': key_value}, response=response)
                    users.objects.filter(login=key_value).update(last_login_ip=ip_address)
                    return response
            else:
                return HttpResponseRedirect('/authorisation/sign_up/')
        else:
            return HttpResponseRedirect('/authorisation/sign_up/')
            # db_execution = users.objects.get(first_login_ip=ip_address, last_login_ip=ip_address)
            # logger.warning(db_execution)
        #logger.info(db_execution.get('login'))
        #if db_execution or users.objects.filter(login=request.COOKIES.get("account_cookie")):
        #return render(request, 'mergeservice/main_page.html', {'Halo': 'Halo!'},)
        # else:
        #     return HttpResponseRedirect('/authorisation/log_in/')

    # def get_queryset(self):
    #     context = super().get_context_data()
    #     dict_1 = {}
    #     logging.error(organisation_needs.objects.all().first())
            # grants.objects.

        #return grants.objects.all()

    def post(self, request, *args, **kwargs):
        #logger.warning(request.POST)
        if "_about_us" in request.POST:
            #logger.warning(model_to_dict(users.objects.all()))
            return HttpResponseRedirect('/about_us/')
        list_with_comp_names = organisations.objects.all().values("name")
        for i in [i.get('name') for i in list(list_with_comp_names)]:
            if f"connect_to_{i}" in request.POST:
                # logger.warning(model_to_dict(users.objects.all()))
                return HttpResponseRedirect(f'/join/{i}/')




#Read about classes and insert another

mergeservice/templates/mergeservice/Authorisation.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Authorisation</title>
    <link rel="stylesheet" href="{% static 'mergeservice/Authorisation.css' %}">
</head>
<body>
    <header></header>
    <section>
        {% if messages %}
        {% for message in messages %}
            <p class="{{ message.tags }}">{{ message }}</p>
        {% endfor %}
        {% endif %}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
        <a href="{% url 'mergeservice:Authorasation' link_name %}">{{ link_name }}</a>
    </section>
    <footer></footer>
</body>
</html>

mergeservice/templates/mergeservice/Cabinet_comapny.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{{ static 'mergeservice/comp_cab.css' }}">
</head>
<body>
    <div class="find_block">
        <button id="button_filter" type="button" onclick="filter_request()"></button>
        <input placeholder="Filter something..." id="input_filter">
    </div>
    <div class="select_section">
        <button class="clicked_but" value='all' type="button">All</button>
        <button value='grants' type="button">Grants</button>
        <button value='requests' type="button">Requests</button>
        <button value='users' type="button">Users</button>
        <button value='confirm' type="button">Confirm</button>
        <button disabled value='filtered' type="button">Filtered</button>
    </div>
    <section>
        {% if dict_info_blocks %}
            {% for cat, text_list in dict_info_blocks.items %}
                {% for text in text_list %}
                    <div class="{{ cat }} checked_block">{{ text }}</div>
                {% endfor %}
            {% endfor %}
        {% else %}
            <div>Something fucked up ▔\▁((.′◔_′◔.))▁/▔ (again....................)</div>
        {% endif %}
    </section>
    <script src="{{ static 'mergeservice/js/comp.js' }}"></script>
</body>
</html>

mergeservice/templates/mergeservice/Create_grant.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Creating a grant</title>
</head>
<body>
<p>Your grant will be checked by admins and your company employers!</p>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Submit</button>
    </form>
</body>
</html>

mergeservice/templates/mergeservice/about_us.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'mergeservice/about_us.css' %}">
</head>
<body>
    <p>{{ object }}</p>
</body>
</html>

mergeservice/templates/mergeservice/company_creating.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'mergeservice/comp_create.css' %}">
</head>
<body>
    {% if messages %}
    {% for message in messages %}
        <p class="{{ message.tags }}">{{ message }}</p>
    {% endfor %}
    {% endif %}
    <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
    </form>
    <button name="back_to_slash" value="Back_TS">Back</button>
</body>
</html>

mergeservice/templates/mergeservice/join_form_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if messages %}
    {% for message in messages %}
        <p class="{{ message.tags }}">{{ message }}</p>
    {% endfor %}
    {% endif %}
  <p>{{ org_name }}</p>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
<!--    <form method="post">-->
<!--        {% if parametres %}-->
<!--        {% for key, value in parametres.items %}-->
<!--        <input id="{{ key }}">-->
<!--        <label for="{{ key }}">{{ key }}</label>-->
<!--        {% endfor %}-->
<!--        <button>Submit</button>-->
<!--        {% else %}-->
<!--        <p>We've got some problems with data, please wait.</p>-->
<!--        {% endif %}-->
<!--    </form>-->
</body>
</html>

mergeservice/templates/mergeservice/main_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'mergeservice/main_page.css' %}">
</head>
<body>
    <header>
        <p>Menu</p>
        <div class="photo_class"></div>
        <div class="floating_account_block">
            <img id="click_menu" src="{% static 'mergeservice/images/acc_photo.webp' %}">
            <div id="list_menu">
                {% if comp_list %}
                {% for comp_name in comp_list %}
                <a href="{% url 'mergeservice:company_cabinet' comp_name %}">{{ comp_name }}</a>
                {% endfor %}
                {% else %}
                <a href="{% url 'mergeservice:Company_creating' %}">Would you like create a company?</a>
                {% endif %}
            </div>
        </div>
    </header>
    <section class="main_window">
        <ul class="tab_menu">
            <li tab="1">Grants</li>
            <li tab="2">Profit Companies</li>
            <li tab="3">Non-profit Companies</li>
        </ul>
        <div class="Line_1">
            <div class="Line_2"></div>
        </div>
        <form method="post">
            {% csrf_token %}
        <div class="grant_window" data-tab="1">
            {% if grants %}
            {% for key_grant, value_grant in grants %}

            {% endfor %}
            {% else %}
            <div class="absent_of_grants">Sorry, but we don't have any grants for this moment.</div>
            {% endif %}
        </div>
        <div class="grant_window" data-tab="2">
            {% if orgs_prof %}
            {% for key_name, value_description in orgs_prof.items %}
            <div>
                <p>{{ key_name }}</p>
                {% for i in value_description %}
                <p>{{ i }}</p>
                {% endfor %}
                <button name="connect_to_{{ key_name }}">Connect</button>
            </div>
            {% endfor %}
            {% else %}
            <div class="absent_of_grants">Sorry, but we don't have any orgs_prof for this moment.</div>
            {% endif %}
        </div>
        <div class="grant_window" data-tab="3">
            {% if orgs_non_prof %}
            {% for key_name, value_description in orgs_non_prof.items %}
            <div>
                <p>{{ key_name }}</p>
                {% for i in value_description %}
                <p>{{ i }}</p>
                {% endfor %}
                <button name="connect_to_{{ key_name }}">Connect</button>
                <button name="see_goal_of_{{ key_name }}">Help</button>
            </div>
            {% endfor %}
            {% else %}
            <div class="absent_of_grants">Sorry, but we don't have any orgs_non_prof for this moment.</div>
            {% endif %}
        </div>
        </form>
    </section>
    <footer>
        <ul>
            <li></li>
        </ul>
        <div>
            <form method="post">
                {% csrf_token %}
                <button name="_about_us">About Us</button>
            </form>
        </div>
    </footer>
    <script src="{% static 'mergeservice/js/main_page.js' %}"></script>
</body>
</html>